ktor:
  application:
    modules:
      - com.dpv.ApplicationKt.module
  deployment:
    port: 8080

dpv:
  db:
    username: root
    password: root
    url: "jdbc:mysql://localhost:3307/dpv-db?rewriteBatchedInserts=true&serverTimezone=UTC&allowMultiQueries=true"
    driver: "com.mysql.cj.jdbc.Driver"

github:
  baseUrl: "https://api.github.com"
  xGithubApiVersion: "2022-11-28"

sync-cronjob:
  expression: "0 0 * * 1" # Every Monday at 00:00 UTC